crab status -d crab_XtoYH_UL2018_RunA_SingleMuon/crab_crab_XtoYH_UL2018_RunA_SingleMuon/
crab status -d crab_XtoYH_UL2018_RunB_SingleMuon/crab_crab_XtoYH_UL2018_RunB_SingleMuon/
crab status -d crab_XtoYH_UL2018_RunC_SingleMuon/crab_crab_XtoYH_UL2018_RunC_SingleMuon/
crab status -d crab_XtoYH_UL2018_RunD_SingleMuon/crab_crab_XtoYH_UL2018_RunD_SingleMuon/
crab status -d crab_XtoYH_UL2018_RunA_EGamma/crab_crab_XtoYH_UL2018_RunA_EGamma/
crab status -d crab_XtoYH_UL2018_RunB_EGamma/crab_crab_XtoYH_UL2018_RunB_EGamma/
crab status -d crab_XtoYH_UL2018_RunC_EGamma/crab_crab_XtoYH_UL2018_RunC_EGamma/
crab status -d crab_XtoYH_UL2018_RunD_EGamma/crab_crab_XtoYH_UL2018_RunD_EGamma/
